apiVersion: v1
kind: Service
metadata:
    name: stratum-{{.Chart.Name }}
    labels:
        name: stratum
spec:
    externalTrafficPolicy: Local
    type: NodePort
    ports:
      - protocol: TCP
        port: 28000
        nodePort: 30001
        name: stratum-p4rt
      - protocol: TCP
        port: 9339
        nodePort: 30002
        name: stratum-gnmi-gnoi
    selector:
        name: stratum
